### PR TITLE
- update for x64

### PR DESCRIPTION
**Pull request by chcg**
- removed outdated ansi support and updated with https://github.com/npp-plugins/plugintemplate v3.1

see https://ci.appveyor.com/project/chcg/nppfavorites/builds/19503142

### CODE REVIEW

**Comment by chcg** [comment]
@heldersepu see https://www.appveyor.com/docs/deployment/github/#provider-settings after adding a secure token to appveyor.yml it is sufficient to add a git tag to create a new release with zips.

**Comment by heldersepu** [comment]
@chcg I guess that is all:
Got the token from:
https://github.com/settings/tokens

Then encrypt it on:
https://ci.appveyor.com/tools/encrypt

That is what we can see here:
https://github.com/heldersepu/nppfavorites/blob/master/appveyor.yml#L64

**Comment by heldersepu** [comment]
@chcg I see artifacts on the build, was the deployment supposed to inject something into the release?

**Comment by chcg** [comment]
@heldersepu Yes it should inject, but there is an issue in creating the zip files contained. I will prepare another PR to correct that.

**Pull request merged**
